---
- hosts: dbservers
  vars_files:
    - vars.yml
    - vault.yml
  tasks:
    - import_tasks: "./tasks/prep.yml"
      tags:
        - prep

    - import_tasks: "./tasks/ssl.yml"
      tags:
        - ssl

    - import_tasks: "./tasks/mysql.yml"
      tags:
        - mysql

    - import_tasks: "./tasks/ufw.yml"
      tags:
        - ufw
