---
- name: Install MySQL
  become: true
  apt:
    state: latest
    name:
      - mysql-server

- name: Check for SSL config (breaks some setup tasks that should already be done)
  become: true
  stat:
    path: /etc/mysql/mysql.conf.d/mysql_ssl.cnf
  register: mysql_ssl_conf

#region mysql_secure_installation
- name: Check if root password is set
  command: "mysql -u root -p'{{ mysql_root_pass }}' -e 'SELECT 1'"
  ignore_errors: yes
  register: mysql_root_response

- name: Set MySQL root password
  become: true
  mysql_user:
    name: root
    password: "{{ mysql_root_pass }}"
    host: "{{ item }}"
  with_items:
    - "::1"
    - "127.0.0.1"
    - "localhost"
  when: mysql_root_response.rc == 1

- name: Remove test database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_pass }}"
    name: test
    state: absent
  when: not mysql_ssl_conf.stat.exists

- name: Remove anonymous users
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_pass }}"
    name: ""
    state: absent
    host_all: yes
  when: not mysql_ssl_conf.stat.exists

- name: Remove remote root access
  command: "mysql -u root -p{{ mysql_root_pass }} -e \"DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');\""
#endregion

- name: Set default character set
  become: true
  copy:
    content: |
      [client]
      default-character-set = utf8mb4

      [mysql]
      default-character-set = utf8mb4

      [mysqld]
      character-set-server = utf8mb4
      collation-server = utf8mb4_unicode_ci
    dest: /etc/mysql/mysql.conf.d/mysql_character_set.cnf

- name: Enable encrypted tables
  become: true
  copy:
    content: |
      [mysqld]
      early-plugin-load=keyring_file.so
    dest: /etc/mysql/mysql.conf.d/mysql_keyring_setup.cnf

# files are in default location, so they do not need to be specified
- name: Configure SSL for MySQL server
  become: true
  copy:
    content: |
      [mysqld]
      require_secure_transport=ON
    dest: /etc/mysql/mysql.conf.d/mysql_ssl.cnf

- name: Prepare remote user
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_pass }}"
    name: "{{ mysql_username }}"
    password: "{{ mysql_user_pass }}"
    state: present
    priv: "*.*:ALL"
    host: "{{ item }}"
  with_items:
    - localhost
    - "%"
  when: not mysql_ssl_conf.stat.exists

- name: Open mysql for remote connections
  become: true
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: "^bind-address"
    line: "bind-address\t= 0.0.0.0"

- name: Restart MySQL service
  become: true
  service:
    name: mysql
    state: restarted
