---
- name: Set timezone to CST
  become: true
  timezone:
    name: America/Chicago

- name: Update apt package manager
  become: true
  apt:
    update_cache: yes

- name: Upgrade existing packages
  become: true
  apt:
    upgrade: safe

- name: Install required python management modules
  become: true
  apt:
    state: latest
    name:
      - python3-mysqldb
      - python3-openssl
